"""Initial migration

Revision ID: 4471f38d6845
Revises: 
Create Date: 2025-10-10 19:53:01.719178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4471f38d6845'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimate_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estimates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('project_location', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('estimate_date', sa.DateTime(), nullable=False),
    sa.Column('prepared_by', sa.String(length=255), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('total_material', sa.Float(), nullable=True),
    sa.Column('total_labor', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['estimate_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estimate_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('section_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtotal_material', sa.Float(), nullable=True),
    sa.Column('subtotal_labor', sa.Float(), nullable=True),
    sa.Column('subtotal_total', sa.Float(), nullable=True),
    sa.Column('estimate_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['estimate_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estimate_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.Enum('SF', 'EA', 'LS', 'LF', 'CY', 'SY', 'TON', 'HR', name='unittype'), nullable=True),
    sa.Column('material_unit_cost', sa.Float(), nullable=True),
    sa.Column('material_amount', sa.Float(), nullable=True),
    sa.Column('labor_unit_cost', sa.Float(), nullable=True),
    sa.Column('labor_amount', sa.Float(), nullable=True),
    sa.Column('total_unit_cost', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('item_type', sa.Enum('SECTION_HEADER', 'LINE_ITEM', 'SUBTOTAL', 'SUB_HEADER', name='itemtype'), nullable=True),
    sa.Column('section_code', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('estimate_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['estimate_items.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['estimate_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estimate_items')
    op.drop_table('estimate_sections')
    op.drop_table('estimates')
    op.drop_table('estimate_templates')
    # ### end Alembic commands ###
